server:
  port: 9998

spring:
  application:
    name: pet-life

  # 数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet_life?characterEncoding=utf8&useSSL=false
    username: root
    password: root

  # redis 配置
  redis:
    host: 127.0.0.1
    pool:
      max-active: 300
      max-idle: 300
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 30000

  # 修改spring匹配规则 兼容Swagger2
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # 设置文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

wechat:
  # 微信小程序wx64cef1828d00a201
#  d49283b33f94066503284a9f1766c2e4
  applet:
    app-id: wx5c6870982b8ecbca
    app-secret: 5c658de0df1ec3dc8468b0ad7cce4b2f
    access-token-api-url: https://api.weixin.qq.com/sns/jscode2session
# 项目相关配置
pet:
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: E:\educationProject\宠物系统\petAdoptApp\upload
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
